version: '2'
services:
  node:
    image: node:9.3.0-alpine
    container_name: web4-node
    ports:
      - "8082:3000"
    volumes:
      - ./app:/app
    working_dir: /app
    command: sh -c "npm install --no-bin-links && npm start"