version: '2'
services:
  node:
    image: node:9.3.0-alpine
    container_name: net1
    ports:
      - "7467:7467"
    volumes:
      - ./app:/app
    working_dir: /app
    command: sh -c "npm install --no-bin-links && npm start"